### PR TITLE
Fixed Unittests and namespace problems

### PR DESCRIPTION
**Pull request by kuborgh-mspindelhirn**
To make this library 100% compatible with composer and it´s autoloading I gave every class it´s own file. Prior to this püatch there were some files with 2 or more classes. 
In addition I fixed some minor bugs ( e.g Added \ before Exceptions because they are in the global namepsace and would not be found in the local namespace )

### CODE REVIEW

**Comment by lpeabody** [comment]
I'm seeing the same thing as echeese.

**Comment by moserware** [comment]
I no longer run PHP. I'd be happy to accept pull requests on this

**Comment by moserware** [comment]
(Apologies for overlooking this so long. It got buried in my email archive. I haven't done any PHP work in the 5 years since writing this port, but was recently re-alerted to this by @lpeabody 's PR #11 )

It looks like I caused a lot of problems when I merged @kuborgh-mspindelhirn 's well-intentioned https://github.com/moserware/PHPSkills/commit/c05b21a15491a145856c7dab9a14057640198293 commit. The `RankSorter` regression was addressed in this pending PR, but several FactorGraph classes were also accidentally broken because they dependend on references, not value copies.

I think what's needed is to carefully go through the changes of https://github.com/moserware/PHPSkills/commit/c05b21a15491a145856c7dab9a14057640198293 and look for cases where reference semantics were changed and make them work with the latest version of PHP. Once that is done and merged, subsequent cleanup (e.g. PSR-4 style things as in #11 ) can happen.

@lpeabody Would you be interested in checking which items done in https://github.com/moserware/PHPSkills/commit/c05b21a15491a145856c7dab9a14057640198293 need to be fixed?

**Comment by lpeabody** [comment]
@moserware thanks for looking at this and pointing out the origin of the conflicts. I'm going to look at this more in depth tomorrow.

**Comment by Zn4rK** [comment]
This is not applicable anymore, thank you so much though!

**Pull request closed without merging**
